Time::DATE_FORMATS[:my_time] = "%A, %B %d, %Y--%-I:%M%p"
Time::DATE_FORMATS[:time_only] = "%-I:%M%p"
Time::DATE_FORMATS[:date_only] = "%A, %B %-d, %Y"
Time::DATE_FORMATS[:short_date_only] = "%-m/%d/%Y"
Time::DATE_FORMATS[:short_date_time] = "%-m/%-d/%Y %-I:%M%p"